// Code generated by gen_appversion.go; DO NOT EDIT.

package main

import (
	"craps/apps"
	"embed"
	"fyne.io/fyne/v2"
)

type AppVersion int

const (
	AppVersion1 AppVersion = iota
	AppVersion2
	AppVersion3
)

func (app AppVersion) String() string {
	switch app {
	case AppVersion1:
		return "V1"
	case AppVersion2:
		return "V2"
	case AppVersion3:
		return "V3"
	default:
		return "Unknown"
	}
}

func (v AppVersion) App(animationFiles embed.FS) (stuff *fyne.Container) {
	switch v {
	case AppVersion1:
		return apps.App1(animationFiles)
	case AppVersion2:
		return apps.App2(animationFiles)
	case AppVersion3:
		return apps.App3(animationFiles)
	default:
		panic("unsupported version")
	}
}
